Repository ConvergenceSwAce/MJS-admin-web, pull requests merged in 2022-11, with the labels that each got.

#4 Chore : file replace
  FE/.gitignore
  FE/package-lock.json
  FE/package.json
  FE/public/favicon.ico
  FE/public/index.html
  FE/public/logo192.png
  FE/public/logo512.png
  FE/public/manifest.json
  FE/public/robots.txt
  FE/src/App.css
  FE/src/App.js
  FE/src/App.test.js
  FE/src/index.css
  FE/src/index.js
  FE/src/logo.svg
  FE/src/reportWebVitals.js
  FE/src/setupTests.js
Labels: ✅완료, 민수

#6 Chore : ignore 업데이트
  FE/.gitignore
Labels: 👀리뷰필요, 민수

#11 Chore : mealinfo 페이지 수정
  FE/.eslintrc.json
  FE/package-lock.json
  FE/package.json
  FE/src/layouts/mealinfo/data/projectsTableData.js
  FE/src/layouts/mealinfo/index.js
  FE/src/layouts/tables/data/authorsTableData.js
  FE/src/routes.js
Labels: ✅완료, 태강

#12 Feat : 식단정보 추가
  FE/.eslintrc.json
  FE/package-lock.json
  FE/package.json
  FE/src/index.js
  FE/src/layouts/mealinfo/data/projectsTableData.js
  FE/src/layouts/mealinfo/index.js
  FE/src/states/index.js
Labels: 👨🏻‍💻개발중, 태강

#13 페이지 내 불필요한 내용 제거
  FE/src/examples/Navbars/DefaultNavbar/DefaultNavbarMobile.js
  FE/src/examples/Navbars/DefaultNavbar/index.js
  FE/src/layouts/authentication/components/BasicLayout/index.js
  FE/src/layouts/authentication/components/CoverLayout/index.js
  FE/src/layouts/authentication/sign-in/index.js
  FE/src/layouts/authentication/sign-up/index.js
  FE/src/layouts/notifications/index.js
Labels: ✅완료, 민수
